version: '3.9'
services:
  postgresdb:
      image: postgres:alpine
      container_name: postgres_container
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=net_worth_calculator_db
        - DATABASE_HOST=postgresdb
        - DATABASE_PORT=9090
      volumes:
        - db-data:/var/lib/postgresql/data
      ports:
        - '5432:5432'

volumes:
 db-data: {}